# Generated by Django 2.0.4 on 2018-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180501_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prifile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
