# Generated by Django 2.0.4 on 2018-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_prifile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prifile_image',
            new_name='profile_image',
        ),
    ]
