# Generated by Django 2.0.4 on 2018-05-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180502_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='creator',
        ),
    ]
